// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_0XFj7HIYB6uOczQHDfvs2s5wSizslJw',
    appId: '1:2907392182:android:82d68727914d17c46abe17',
    messagingSenderId: '2907392182',
    projectId: 'warrior-5f65c',
    databaseURL: 'https://warrior-5f65c.firebaseio.com',
    storageBucket: 'warrior-5f65c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3B5nPZHLqUoLvGxRrhreLmWiwCjofnCk',
    appId: '1:2907392182:ios:7b27b3276923f9636abe17',
    messagingSenderId: '2907392182',
    projectId: 'warrior-5f65c',
    databaseURL: 'https://warrior-5f65c.firebaseio.com',
    storageBucket: 'warrior-5f65c.appspot.com',
    androidClientId: '2907392182-6i0h4rhndvatcq17vqcrhvr6c613n9hc.apps.googleusercontent.com',
    iosClientId: '2907392182-nnrnumf1r0bepavjbk9h7u7bktsqg9fr.apps.googleusercontent.com',
    iosBundleId: 'com.task.githubIssueTracker',
  );
}
